### ISSUE TITLE
Does not work with PHP 8.1

### ISSUE THREAD

**Issue by catharsis71** [UberGallery/UberGallery#81]
Upgraded my server (was on PHP 7.4 previously) and UberGallery no longer works

```
[Thu Dec 22 09:31:28.385394 2022] [proxy_fcgi:error] [pid 140312:tid 281472936992960] [client 2603:c020:c00a:c00:195:242:99:71:35790] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function UberGallery::_errorHandler(), 4 passed in /var/www/ipv6/files/crackypics/2004-December/resources/UberGallery.php on line 198 and exactly 5 expected in /var/www/ipv6/files/crackypics/2004-December/resources/UberGallery.php:1283\nStack trace:\n#0 /var/www/ipv6/files/crackypics/2004-December/resources/UberGallery.php(198): UberGallery->_errorHandler()\n#1 /var/www/ipv6/files/crackypics/2004-December/index.php(10): UberGallery->readImageDirectory()\n#2 {main}\n  thrown in /var/www/ipv6/files/crackypics/2004-December/resources/UberGallery.php on line 1283'
```

**Comment by catharsis71** [comment]
Also works with PHP 8.0 so 8.1 seems to be the break point

**Comment by catharsis71** [comment]
Tested with these PHP versions:

```
7.4.33 - works
8.0.29 - works
8.1.21 - broken
8.2.8 - broken
8.3.0alpha3 - broken
```
